### ISSUE TITLE
请教下，启动成功了没输出插桩的内容，是否我配置有问题？

### ISSUE THREAD

**Issue by zkohrileung** [izerui/java-runner-feedback#1]
启动如图：<img width="1213" alt="image" src="https://github.com/izerui/java-runner-feedback/assets/12380575/39858c26-b99b-40de-969c-6ebe8adedd3f">
配置如图：
<img width="1047" alt="image" src="https://github.com/izerui/java-runner-feedback/assets/12380575/b3503c02-6b16-4840-903a-774ca7f2606b">

我是用idea的vm option配置启动的，访问http://localhost:8080/控制台会输出sql，但是没readme那图片的方法树的内容输出，也没看到项目有此类文件的新增。是我配错了什么吗？

另外请教多一个问题，是关于调试的。
本工程调试: 在sample模块的application运行配置中

添加 vm options（这个要配啥？ com.github.izerui.Agent吗？）
添加 agent模块的 前置build任务clean package（这个是否配好模块依赖就行？
`<modules>
	<module>runner-feedback-agent</module>
	<module>runner-feedback-core</module>
</modules>`

谢谢。

**Comment by izerui** [comment]
需要在maven依赖中增加 runner-feedback-core 的依赖，然后 
添加切入口：
`@Tracer("切入口")
public RespVO<PageVo<BusinessTaskVo>> findTaskList(@RequestBody BaseQueryVo vo) {
    // ...
}`
